### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by cdaringe** [fgardt/semantic-release-factorio#1]
this seems like a great idea! would love some docs to try it out

**Comment by fgardt** [comment]
I haven't worked on this for a bit but you can see a working github actions config in my mod test repo here: https://github.com/fgardt/factorio-test-mod
_(also take a look at `.gitattributes` and `.releaserc`)_

I'll add some docs at a later time when I get to it again

**Comment by fgardt** [comment]
so its been a while but I finally came around to document the template repo here: \
https://github.com/fgardt/factorio-mod-template. 

Feel free to try it out and report your findings
